CREATE DATABASE IF NOT EXISTS movie_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE movie_db;

-- CREATE TABLE users(
-- id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    username VARCHAR(50) NOT NULL UNIQUE,
--    email VARCHAR(100) NOT NULL UNIQUE,
--    password VARCHAR(255) NOT NULL, role ENUM('USER', 'ADMIN') DEFAULT 'USER',
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );

-- DROP TABLE IF EXISTS movies;
CREATE TABLE IF NOT EXISTS movies(
	id  BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    director VARCHAR(100) NOT NULL,
    release_year INT,
    poster_url VARCHAR(500),
    description TEXT,
    genre VARCHAR(100)
--  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);